name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.1"
          bundler-cache: true

      - name: Database (test)
        run: bundle exec rails db:test:prepare

      - name: RSpec
        run: bundle exec rspec
